@
module.exports = {
  '加载班级和学生信息失败，已使用示例数据': 'Failed to load class and student info, using example data',
  '退出登录成功': 'Logout successful',
  '登出失败，但已清除本地会话': 'Logout failed on server, cleared local session',
  'AI 回复已收到': 'AI response received',
  'AI 服务异常': 'AI service exception',
  '请重试': 'Please try again',
  '请输入 PPT 主题': 'Please enter PPT topic',
  'PPT 大纲生成失败': 'Failed to generate PPT outline',
  'PPT 大纲已生成，正在创建任务...': 'PPT outline generated, creating task...',
  'PPT 任务创建失败': 'Failed to create PPT task',
  'PPT 任务已创建': 'PPT task created',
  '状态': 'Status',
  'PPT 生成超时，请稍后手动查询或刷新页面': 'PPT generation timed out, manually query or refresh later',
  'PPT 生成成功！': 'PPT generation successful!',
  'PPT 生成失败': 'PPT generation failed',
  '请输入考察知识点': 'Please enter knowledge points',
  '请选择题型': 'Please select question types',
  '题目生成成功，共': 'Questions generated successfully, total',
  '题': 'questions',
  '题目生成后端返回为空，请检查参数是否正确': 'Backend returned empty for questions, please check parameters',
  '后端网关超时，正在重试...': 'Backend gateway timeout, retrying...',
  '后端网关超时（504）：AI 处理请求耗时过长，已重试': 'Backend gateway timeout (504): AI processing too long, retried',
  '次仍未成功。\\n\\n建议：\\n1. 减少题目数量重试\\n2. 等待几分钟后重试\\n3. 检查后端服务状态\\n→ 管理员：请增加 Nginx proxy_read_timeout 配置': 'times. Suggestions: 1. Reduce questions 2. Wait and retry 3. Check backend. Admin: increase Nginx proxy_read_timeout.',
  '请求超时：后端处理时间过长，请稍后重试或检查后端服务是否正常运行': 'Request timeout: backend processing too long, please retry later',
  '请求参数错误（400）：请检查填写的知识点、难度等参数是否正确': 'Parameter error (400): Please check knowledge point, difficulty, etc.',
  '登录已过期，请重新登录': 'Login expired, please login again',
  '题目生成失败': 'Failed to generate questions',
  '请先生成题目': 'Please generate questions first',
  '请至少选择一个班级或学生': 'Please select at least one class or student',
  '作业发布成功': 'Homework published successfully',
  '作业发布失败': 'Failed to publish homework',
  '作业发布失败，请重试': 'Failed to publish homework, please try again',
  '请选择文件': 'Please select a file',
  '请填写所属课程 ID': 'Please fill in the course ID',
  '上传成功': 'Upload successful',
  '上传失败': 'Upload failed',
  '上传过程出错': 'Upload process error',
  '同步文件数据失败': 'Failed to sync file data',
  '发布成功': 'Publish successful',
  '发布失败': 'Publish failed',
  '系统异常': 'System exception',
  '撤回成功': 'Revoke successful',
  '撤回失败': 'Revoke failed',
  '确定要删除这个资源吗？': 'Are you sure you want to delete this resource?',
  '提示': 'Notice',
  '删除成功': 'Delete successful',
  '删除失败': 'Delete failed',
  '该文件': 'This file',
  '暂不支持在线预览，请下载后查看': 'Does not support online preview, please download',
  '该文件暂时不支持直接在线预览': 'This file currently does not support direct online preview',
  '预览链接获取失败': 'Failed to get preview link',
  '开始请求下载，请稍候...': 'Requesting download, please wait...',
  '开始下载': 'Starting download',
  '下载失败，请重试': 'Download failed, please try again',
  '参数缺失': 'Missing parameters',
  '未找到该学生的提交记录。请检查参数是否正确。': 'Could not find submission record for this student. Please check parameters.',
  '加载作业失败': 'Failed to load homework',
  '加载失败': 'Failed to load',
  '请输入分数': 'Please enter score',
  '批改成功！': 'Grading successful!',
  '批改失败': 'Grading failed',
  '请先登录': 'Please login first',
  '← 返回': '← Back',
  '?? 作业批改': '?? Homework Grading',
  '的答案': '\\'s answers',
  '已批改': 'Reviewed',
  '待批改': 'Pending',
  '【选择题】': '[Multiple Choice]',
  '【判断题】': '[True/False]',
  '学生答案:': 'Student Answer:',
  '未答': 'Not answered',
  '标准答案:': 'Standard Answer:',
  '解析:': 'Explanation:',
  '暂无解析': 'No explanation available',
  '学生备注:': 'Student Note:',
  '批改评分': 'Grading Score',
  '分数（0-100）': 'Score (0-100)',
  '反馈意见': 'Feedback',
  '例如：解答很详细，思路清晰...': 'e.g. Detailed explanation, clear logic...',
  '确认提交批改': 'Confirm Submit Grading'
}
@
