@
const fs = require('fs');
const path = require('path');

const msgDict = {
  '加载班级和学生信息失败，已使用示例数据': 'load_class_failed',
  '退出登录成功': 'logout_success',
  '登出失败，但已清除本地会话': 'logout_failed_cleared',
  'AI 回复已收到': 'ai_reply_received',
  'AI 服务异常': 'ai_service_exception',
  'AI 服务连接失败: ': 'ai_service_conn_failed',
  '请重试': 'please_retry',
  '请输入 PPT 主题': 'please_enter_ppt_topic',
  'PPT 大纲生成失败': 'ppt_outline_failed',
  'PPT 大纲已生成，正在创建任务...': 'ppt_outline_generated_task',
  'PPT 任务创建失败': 'ppt_task_failed',
  'PPT 任务已创建 (ID: ': 'ppt_task_created_id',
  ')，状态: ': 'status_is',
  'PPT 生成超时，请稍后手动查询或刷新页面': 'ppt_timeout_query_later',
  'PPT 生成成功！': 'ppt_success',
  'PPT 生成失败: ': 'ppt_failed',
  '请输入考察知识点': 'enter_knowledge_points',
  '请选择题型': 'select_question_type',
  '题目生成成功，共 ': 'questions_success_total',
  ' 题': 'questions_count',
  '题目生成后端返回为空，请检查参数是否正确': 'questions_empty_check_params',
  '后端网关超时，正在重试... ': 'gateway_timeout_retrying',
  '后端网关超时（504）：AI 处理请求耗时过长，已重试 ': 'gateway_timeout_504_retried',
  ' 次仍未成功。\\n\\n建议：\\n1. 减少题目数量重试\\n2. 等待几分钟后重试\\n3. 检查后端服务状态\\n→ 管理员：请增加 Nginx proxy_read_timeout 配置': 'times_failed_suggestions',
  '请求超时：后端处理时间过长，请稍后重试或检查后端服务是否正常运行': 'req_timeout_backend_long',
  '请求参数错误（400）：请检查填写的知识点、难度等参数是否正确': 'req_param_err_400',
  '登录已过期，请重新登录': 'login_expired',
  '题目生成失败: ': 'question_gen_failed',
  '请先生成题目': 'please_gen_questions_first',
  '请至少选择一个班级或学生': 'select_class_or_student',
  '作业发布成功': 'hw_publish_success',
  '作业发布失败': 'hw_publish_failed',
  '作业发布失败，请重试': 'hw_publish_failed_retry',
  '请选择文件': 'please_select_file',
  '请填写所属课程 ID': 'please_fill_course_id',
  '上传成功': 'upload_success',
  '上传失败': 'upload_failed',
  '上传过程出错': 'upload_process_err',
  '同步文件数据失败': 'sync_file_data_failed',
  '发布成功': 'publish_success',
  '发布失败': 'publish_failed',
  '系统异常': 'system_exception',
  '撤回成功': 'revoke_success',
  '撤回失败': 'revoke_failed',
  '确定要删除这个资源吗？': 'confirm_delete_resource',
  '提示': 'notice',
  '删除成功': 'delete_success',
  '删除失败': 'delete_failed',
  '暂不支持在线预览，请下载后查看': 'no_online_preview',
  '该文件暂时不支持直接在线预览': 'file_no_online_preview',
  '预览链接获取失败': 'preview_link_failed',
  '开始请求下载，请稍候...': 'req_download_wait',
  '开始下载': 'start_download',
  '下载失败，请重试': 'download_failed_retry',
  '参数缺失': 'missing_params',
  '未找到该学生的提交记录。请检查参数是否正确。': 'no_student_record',
  '加载作业失败': 'load_hw_failed',
  '加载失败: ': 'load_failed',
  '请输入分数': 'please_enter_score',
  '批改成功！': 'grading_success',
  '批改失败': 'grading_failed',
  '批改失败: ': 'grading_failed_colon',
  '请先登录': 'please_login_first'
};

const gradingDict = {
  '← 返回': 'btn_back',
  '?? 作业批改': 'title_homework_grading',
  ' 的答案': 's_answers',
  '已批改': 'status_reviewed',
  '待批改': 'status_pending',
  '【选择题】': 'type_choice',
  '【判断题】': 'type_true_false',
  '学生答案:': 'lbl_student_answer',
  '未答': 'lbl_not_answered',
  '标准答案:': 'lbl_standard_answer',
  '解析:': 'lbl_explanation',
  '暂无解析': 'lbl_no_explanation',
  '学生备注:': 'lbl_student_note',
  '批改评分': 'title_grading_score',
  '分数（0-100）': 'placeholder_score',
  '反馈意见': 'title_feedback',
  '例如：解答很详细，思路清晰...': 'placeholder_feedback',
  '确认提交批改': 'btn_submit_grading'
};

// ... write script to apply this automatically
@
